### ISSUE TITLE
application get error  Illegal instruction (core dumped)?

### ISSUE THREAD

**Issue by bluesky1308** [borarak/tensorflow2_cpp#1]
Hello Bro,

When I implement project with your instruction, i build get_prediction file like below:

![Screenshot_1](https://user-images.githubusercontent.com/16258812/99077120-9a447d00-25ff-11eb-9912-bbfd0bab4fe1.jpg)

I debug and I see tensorflow meet error (sample #include "tensorflow/cc/saved_model/loader.h"). However, when i import tensorflow on python, It work well.

Could you give me any ways to resolve it.

**Comment by borarak** [comment]
You need to provide additional parameters. The template is here: https://github.com/borarak/tensorflow2_cpp#predict

Hope that fixes it

**Comment by bluesky1308** [comment]
> You need to provide additional parameters. The template is here: https://github.com/borarak/tensorflow2_cpp#predict
> 
> Hope that fixes it

Thank you for replying, However I edited the file for only #include tensorflow like saved_model_loader.h. I debug and I see the error cause by Include Tensorflow

**Comment by borarak** [comment]
@bluesky1308 Could you show me the edited script you are trying?

**Comment by uranusx86** [comment]
in https://github.com/borarak/tensorflow2_cpp/blob/c7ae6b5c7c38432d43523b362f696ad48bcaf39d/saved_model_loader.h#L113
change vector<string> = {{ ....  }}   to vector<string> = { .... }
